ARG BASE_IMAGE_ARG=registry.access.redhat.com/ubi8:latest
FROM ${BASE_IMAGE_ARG}
ARG TARGET_ARCH=amd64

RUN yum -y install python3.11 \
    python3.11-devel \
    python3.11-pip \
    mesa-libGL \
    python3.11-tkinter \
    xz \
    gcc

# Installing ffmpeg via relies on the rpmfusion repo and SDL2
# The SDL2 yum package is not currently available in ubi8
# Consequently, we download and install ffmpeg as a statically
# linked binary below.
WORKDIR /code
ADD https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-$TARGET_ARCH-static.tar.xz /code
RUN tar -xf ffmpeg-*-$TARGET_ARCH-static.tar.xz && \
    cp /code/ffmpeg-*-$TARGET_ARCH-static/ffmpeg /usr/local/bin && \
    cp /code/ffmpeg-*-$TARGET_ARCH-static/ffprobe /usr/local/bin

ENV PYTHONPATH=/code

COPY requirements.txt /code/
RUN python3 -m pip install -r requirements.txt && \
    python3 -m pip install pip-licenses && \
    pip-licenses
ENV PATH=$HOME/.local/bin:$PATH