# This file provides the data paths for the example_scene_reconstruction.py example.
# To use this file, copy it to a new filename and update the values below to point at your data source.
# Original file:
#    <OpenCSP_code_dir>/example/scene_reconstruction/example_scene_reconstruction_ctemp.ini

[Default]
# Whether to output detailed progress output, intermediate calculation results, etc.
verbose = True

# Directory to find input files.
dir_input = C:\ctemp\OpenCSP_ctemp\example_data_large\scene_reconstruction\input

# Directory to write output files.
dir_output = C:\ctemp\OpenCSP_ctemp\example_data_large\scene_reconstruction\example_scene_reconstruction_output
