# This file provides the data paths for the "example_scene_reconstruction.py" example,
# executed against data placed in the "C:\ctemp\OpenCSP_example_data" directory.
#
# To use this file for the ctemp data location, copy the released OpenCSP data from:
#
#     https://opencsp.sandia.gov
#     --> How to Participate
#     --> Access OpenCSP
#     --> shared box.com link
#     --> OpenCSP_Data
#     --> OpenCSP_SampleData
#     --> SceneReconstruction
#     --> SceneReconstructionData_v1.1.zip
#
# Download the .zip file, then unzip the file to produce an unzipped 
# directory "SceneReconstructionData_v1.1" which in turns contains a 
# directory "scene_reconstruction".  Then move the "scene_reconstruction"
# directory into the "C:\ctemp\OpenCSP_example_data" directory, 
# to produce the directory structure:
#
#     C:\ctemp\OpenCSP_example_data\scene_reconstruction\input\...
#
# After this, the "example_scene_reconstruction.py" script should run without modification, by executing the following:
#    1.  Start a powershell.
#    2. Ensure the OpenCSP virtual environment is activated.
#    3. Navigate to the directory containing example_scene_reconstruction.py.
#    4. Execute the following command:
#          python example_scene_reconstruction.py --verbose -s C:\ctemp\OpenCSP_example_data\scene_reconstruction\input\example_scene_reconstruction_settings_ctemp.ini
#       The script should run, writing to an "output" subdirectory placed next to the input directory.


[Default]
# Whether to output detailed progress output, intermediate calculation results, etc.
verbose = True
# Directory to find input files.
dir_input = C:\ctemp\OpenCSP_example_data\scene_reconstruction\input\LabScene\2_Data
# Directory to write output files.
dir_output = C:\ctemp\OpenCSP_example_data\scene_reconstruction\output\LabScene\3_Post
