[Default]
source_image_desc = Single_NSTTF_Facet_0900
nosun_dir = C:\ctemp\OpenCSP_example_data\enclosed_energy\input\HeliostatsSpotSize\2_Data\0900_NoSun\PixelData_Images
# In range below, no space allowed between comma and next entry.
nosun_images_range = 20241123_090715.90_1123_0900_NoSun_Raw.png,20241123_090721.58_1123_0900_NoSun_Raw.png
onsun_dir = C:\ctemp\OpenCSP_example_data\enclosed_energy\input\HeliostatsSpotSize\2_Data\0900_OnSun\PixelData_Images
# In range below, no space allowed between comma and next entry.
onsun_images_range = 20241123_090823.13_1123_0900_SF_Raw.png,20241123_090823.68_1123_0900_SF_Raw.png
output_dir = C:\ctemp\OpenCSP_example_data\enclosed_energy\output