# This file provides the data paths for the "enclosed_energy.ipynb" example notebook,
# executed against data placed in the "C:\ctemp\OpenCSP_example_data" directory.
#
# To use this file for the ctemp data location, copy the released OpenCSP data from:
#
#     https://opencsp.sandia.gov
#     --> How to Participate
#     --> Access OpenCSP
#     --> shared box.com link
#     --> OpenCSP_Data
#     --> OpenCSP_SampleData
#     --> SpotAnalysis
#     --> EnclosedEnergy_v1.1.zip
#
# Unzip and place the enclosed directory within the directory:
#
#     C:\ctemp\OpenCSP_example_data\enclosed_energy\
#
# This will produce a directory structure:
#
#     C:\ctemp\OpenCSP_example_data\enclosed_energy\EnclosedEnergyData_v1.1\
#
# Then rename "EnclosedEnergyData_v1.1" to "input", producing:
#
#     C:\ctemp\OpenCSP_example_data\enclosed_energy\input\
#
# After this, the "enclosed_energy.ipynb" notebook should run without modification,
# writing to an "output" subdirectory placed next to the input directory.

[Default]
source_image_desc = Single_NSTTF_Facet_0900
nosun_dir = C:\ctemp\OpenCSP_example_data\enclosed_energy\input\HeliostatsSpotSize\2_Data\0900_NoSun\PixelData_Images
# In range below, no space allowed between comma and next entry.
nosun_images_range = 20241123_090715.90_1123_0900_NoSun_Raw.png,20241123_090721.58_1123_0900_NoSun_Raw.png
onsun_dir = C:\ctemp\OpenCSP_example_data\enclosed_energy\input\HeliostatsSpotSize\2_Data\0900_OnSun\PixelData_Images
# In range below, no space allowed between comma and next entry.
onsun_images_range = 20241123_090823.13_1123_0900_SF_Raw.png,20241123_090823.68_1123_0900_SF_Raw.png
output_dir = C:\ctemp\OpenCSP_example_data\enclosed_energy\output