# This file provides the data paths for the target_identification.ipynb example notebook.
# To use this file, copy it to "experiment_settings.ini" and update the values below to point at your data source.
# Original file: example/target_identification/experiment_settings_example.ini

[Default]
bcs_images_dir = /path/to/experiments/2_Data/BCS_data
heliostat_name_regex = .*(09E10).*
nosun_name_regex = .*(NoSun).*
process_dir = /path/to/experiments/3_Process
mask_image_path_name_ext = /path/to/experiments/1_Plan/target_board_mask.png