# This file provides the data paths for the "target_identification.ipynb" example notebook,
# executed against data placed in the "C:\ctemp\OpenCSP_example_data" directory.
#
# To use this file for the ctemp data location, copy the released OpenCSP data from:
#
#     https://opencsp.sandia.gov
#     --> How to Participate
#     --> Access OpenCSP
#     --> shared box.com link
#     --> OpenCSP_Data
#     --> OpenCSP_SampleData
#     --> SpotAnalysis
#     --> TargetIdentification_v1.1.zip
#
# Unzip and place the enclosed directory within the directory:
#
#     C:\ctemp\OpenCSP_example_data\target_identification\
#
# This will produce a directory structure:
#
#     C:\ctemp\OpenCSP_example_data\target_identification\TargetIdentificationData_v1.1\
#
# Then rename "TargetIdentificationData_v1.1" to "input", producing:
#
#     C:\ctemp\OpenCSP_example_data\target_identification\input\
#
# After this, the "target_identification.ipynb" notebook should run without modification,
# writing to an "output" subdirectory placed next to the input directory.

[Default]
nosun_dir  = C:\ctemp\OpenCSP_example_data\target_identification\input\HeliostatPointing\2_Data\NoSun
nosun_desc = No Sun
onsun_dir  = C:\ctemp\OpenCSP_example_data\target_identification\input\HeliostatPointing\2_Data\OnSun
onsun_desc = 9E10
mask_image_path_name_ext = C:\ctemp\OpenCSP_example_data\target_identification\input\HeliostatPointing\1_Plan\target_board_mask.png
output_dir = C:\ctemp\OpenCSP_example_data\target_identification\output
